#!/bin/bash

# edit-symbolic-link -- nautilus-script do edycji dowiązania
# wersja: 2011.01.01
# autor: borzole (jedral.one.pl)

LINK="${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS%?}"
# warunek: to musi być link, inaczej żegnamy się
if [ ! -h "$LINK" ] ; then
	zenity --error --text="to nie jest link:\n $LINK"
	exit 0
fi

PATH_ABS=$(readlink -f "$LINK")
PATH_RELATIVE=$(readlink "$LINK")

# pobranie nowej ścieżki docelowej
destination(){
	zenity --title="${0##*/}" --width=500 \
		--text="Link symboliczny: \n$LINK
		\nŚcieżka absolutna: \n$PATH_ABS
		\nŚcieżka relatywna:" \
		--entry --entry-text "$PATH_RELATIVE"
}
DESTINATION="$(destination)"
# jeśli klinięto OK, usuń link i utwórz nowy
if [ $? -eq 0 ] ; then
	rm -f "$LINK"
	ln -s "$DESTINATION" "$LINK"
fi
