#!/bin/bash

# readlink-dirname : otwiera folder do którego prowadzi link symboliczny

abs_path(){
	readlink -f "${NAUTILUS_SCRIPT_CURRENT_URI#file://}"
}

zenity --error --text="$(abs_path)"
xdg-open "$(abs_path)"

