#!/bin/bash

# readlink-file : otwiera folder do którego prowadzi link symboliczny zaznaczonego pliku

file=$(echo -e "${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS}" | head -n 1)
abs=$(readlink -f ${file})
xdg-open "${abs%/*}"
