#!/bin/bash 

# oprawka z zenity do On/Off $1 (default'owo conky)
# by borzole.one.pl

# dobre do skrótów na pulpicie

name=${1:-conky}
# ------------------------------------------------------------------------------
zenity --question --title="$name"  --text "On / Off $name ?" \
		--ok-label="ON :: $name" \
		--cancel-label="OFF :: $name" \

[ $? == 0 ] && $name || killall $name

# ------------------------------------------------------------------------------
