#!/bin/bash 

# rm0dir - usuwa puste katalogi
# by borzole.one.pl

index(){
	dir="$@"
	cd "$dir"
	
	ile=$(find . -xtype f -exec echo '{}' \; 2>/dev/null | wc -l )
	if [ "$ile" == 0 ] ;then
		echo -e $ile =  $dir
		cd ..
		rm -rf "$dir"
	fi
}

menu(){
case "$1" in
	-i | --index )
		shift
		index "$@"
		;;
	-a | --all )
		find . -follow -type d -exec "$0" --index "{}" \;	2>/dev/null
		;;
	*)
		echo help
		;;
esac
}
if [ -n "$1" ]  ; then 
	menu "$@"
else
	echo -e "podaj argument \n ${0##*/} -a, -i <path>"
fi
