#!/bin/bash

# by borzole.one.pl
name=conky

_restart(){
	echo killall $name
	echo sleep 2
	sllep
	echo $name
	
}

_menu(){
	# funkcja zwraca drugą kolumnę 
	# UWAGA na spacje/tabulatory po "\"
	zenity --title="$name"  --text "On / Off $name" \
		--list --column "wybierz" --column "polecenie do wykonania" \
			"$name on" 			"$name"\
			"$name off" 			"killall $name"\
 			"$name reset" 		"_restart"\
		--print-column=2 --hide-column=2
}
# WYBÓR: co zwraca funkcja _menu
#echo "$(_menu)" | zenity --text-info

# OUT: co daje na wyjściu to polecenie
#$(_menu) | zenity --text-info --title="Debuger" --width=700 --height=500

# ERROR: tylko błędy na wyjściu (kolejność 2>&1 i devnull jest istotna )
#$(_menu) 2>&1 >/dev/null  | zenity --text-info --title="Debuger" --width=700 --height=500

# OUT+ERROR: całość
#$(_menu) 2>&1 | zenity --text-info --title="Debuger" --width=700 --height=500

# ostateczna forma bez komunikatów
# $(_menu)



# TODO:
# dodać --radiolist z auto ustawionym statusem na podstawie PID
# ps -C someprogram && ustaw na OFF || ustaw na ON

_menu2(){
	# funkcja zwraca drugą kolumnę 
	# UWAGA na spacje/tabulatory po "\"
	zenity --title="$name"  --text "On / Off $name" \
		--list  --radiolist --width=500 --height=300 \
		--column="radiolist" --column "wybierz" --column "polecenie do wykonania" \
			FALSE		"$name on" 			"$name"\
			TRUE		"$name off" 			"killall $name"\
 			FALSE		"$name reset" 		"_restart"\
		--print-column=3 --hide-column=3
}
#echo 
$(_menu2) 2>&1 | zenity --text-info --title="Debuger" --width=700 --height=500
