#!/bin/bash

# -------------------------------------------------------------------
# zman.sh -- otwiera stronę man w domyślnym edytorze
# -------------------------------------------------------------------
getManPage()
{
	zenity --title "${0##*/}" --entry --text "man: " 
}
# -------------------------------------------------------------------
# test: czy są X-y (w końcu to graficzna aplikacja :P)
[ -z "$DISPLAY" ] && exit 1

MAN_PAGE="$@"
# jeśli nazwa strony nie została podana jako parametr to wyświetli się okienko
if [ -z "$MAN_PAGE" ] ; then
	MAN_PAGE=$(getManPage)
	[ -z "$MAN_PAGE" ] && exit 0
fi
# -------------------------------------------------------------------
# TEST: czy podano nr. strony man
# 	wystarczy sprawdzenie czy zawiera spację, 
# 	jeśli strona nie istnieje to wychwyci to późniejszy test
echo $MAN_PAGE | grep ' '
RC=$?
# -------------------------------------------------------------------
# plik na stronę man w formacie: strona(2).man
if [ $RC != 0 ] ; then
	NR=1
	PAGE=$MAN_PAGE
else
	NR=$(echo $MAN_PAGE | cut -d' ' -f1)
	PAGE=$(echo $MAN_PAGE | cut -d' ' -f2)
fi
MAN_FILE="${HOME}/${PAGE}(${NR}).man"
# -------------------------------------------------------------------
# TEST: czy jest taka strona man
# UWAGA!
# 	parametr $MAN_PAGE może zawierać również nr. strony
# 	dlatego nie należy umieszczać go w ""
man $MAN_PAGE > /dev/null
RC=$?
# -------------------------------------------------------------------
# wykonanie
if [ $RC == 0 ] ; then
	man $MAN_PAGE | col -b > $MAN_FILE
	xdg-open $MAN_FILE
else
	MSG="Nie ma strony: $MAN_PAGE"
	zenity --title ${0##*/} --error --text "$MSG" 
	echo "$MSG" >&2	
	exit 1
fi
