#!/bin/bash

menu(){
	# okno z listą funkcji
	zenity 	--title="$TITLE"  --text "Drobne ustawienia i hopa :)" \
		--list  --radiolist --width=400 --height=200 \
		--column="todo" --column "polecenie do wykonania" \
			TRUE			"--bg-center"\
			FALSE			"--bg-scale"\
			FALSE			"--bg-seamless"\
		--print-column=2
}
# ------------------------------------------------------------------------------
feh $(menu) $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS
