#!/bin/bash

# ukrywa pliki w Nautilus

touch $PWD/.hidden

echo "$NAUTILUS_SCRIPT_SELECTED_URIS" |
	while read -r uri ; do
		uri=${uri##file://}
		echo ${uri##*/} | sed 's:%20: :g' | tee -a $PWD/.hidden
	done
