#!/bin/bash

# readlink-file : otwiera folder zawierający plik do którego prowadzi link symboliczny


for path in "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" ; do
	zenity --error --text="$path"
done
exit
abs=$(readlink -f "$file")
xdg-open "${abs%/*}"
