#!/bin/bash

# readlink-file : otwiera folder zawierający plik do którego prowadzi link symboliczny

zenity --error --text="$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS"
exit
abs=$(readlink -f "$file")
xdg-open "${abs%/*}"
