#!/bin/bash

# readlink-file : otwiera folder zawierający plik do którego prowadzi link symboliczny


while read -r path  ; do
	[ ${#path} != 0 ] && zenity --error --width=$((${#path} * 10)) --text="$path"
done < <(echo -e "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS")
exit
abs=$(readlink -f "$file")
xdg-open "${abs%/*}"
