#!/bin/sh
if [[ -n "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" ]]
then
    quoted=$(echo -e "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" | 
             awk 'BEGIN { FS = "\n" } { printf "\"%s\" ", $1 }' | sed -e s#\"\"##)
    beesu - ghex2 "$quoted"
fi
# F12
