#!/bin/bash

# wykonaj skrypt w terminalu
# Uwaga! w ścieżce do skryptu nie może być spacji
# problem dotyczy gnome-terminal nie xterm

# Check if CMD is set, default to ${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS%?}
: ${CMD:="${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS%?}"}

# jeśli zaznaczony był katalog
[[ -d $CMD ]] && CMD="echo $CMD jest katalogiem"
[[ -f $CMD ]] && CMD="echo $CMD nie ma atrybutu wykonywania ( chmod +x skrypt )"

# TEST: czy jest zainstalowany gnome-terminal
which gnome-terminal >/dev/null 2>/dev/null
if [ $? -eq 0 ] ; then
	# "Hold" jest profilem, w którym terminal nie jest zamykany po zakończeniu polecenia
	gnome-terminal --profile=Hold -e "$CMD"
else
	xterm -hold -e "$CMD"
fi

