#!/bin/bash

# wykonaj skrypt w terminalu

which gnome-terminal >/dev/null 2>/dev/null
	&& gnome-terminal --profile=Hold -e "${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS%?}"
	|| xterm -hold -e "${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS%?}"

# "Hold" jest profilem, w którym terminal nie jest zamykany po zakończeniu polecenia
