#!/bin/bash

# do otwierania PLIKU
cmd="geany $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS"

# do otwierania KATALOGU nautilusem
#cmd="nautilus ${NAUTILUS_SCRIPT_CURRENT_URI##file://}"

# do otwierania KATALOGU w terminalu
#cmd="gnome-terminal ${NAUTILUS_SCRIPT_CURRENT_URI##file://}"

# DEBUG - odznacz by zobaczyć co tak naprawdę zawiera parametr $cmd
echo "$cmd" | zenity --text-info

#zsudo.sh "$cmd"
