#!/bin/bash

#Get the new folder name to be created in this folder
export newfoldername=`zenity --entry --text="Type the name of the new project folder to create"`
if ["$newfoldername" == "" || "$newfoldername" == 0]; then
    exit 0
fi

#Remove the file:// at the beginning of the $NAUTILUS_SCRIPT_CURRENT_URI variable
basefolder=`echo "$NAUTILUS_SCRIPT_CURRENT_URI" | awk '{ print substr( $0, 8, length($0) ) }'`

#Create the new project folder
mkdir "$basefolder/$newfoldername"

#Modify the lines below to create different directory names for your use of the script
mkdir -p "$basefolder/$newfoldername"/{lib/ext,bin,src,doc/{pl/{html,pdf},en},test/stat}

exit 0
