name: Run tests and publish
 
on:
  push:
    branches:
      - master
      - beta
  pull_request:
  
  
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Odpalaj
      run : |
       sudo pwd
       sudo apt update -y
       sudo apt install wget -y
       ping -c 1 onet.pl
       
