name: Testowanie GA 01

jobs:
  kaszanka:
    runs-on: ubuntu-latest
    steps:
    - name: krok pierwszy
        run: |
        ping onet.pl
        pwd
        ls -la
        uname -a
        uptime
        sudo id
